name: Setup SWI-Prolog

description: Installs the specified SWI-Prolog version

inputs:
  swi-prolog-branch:
    description: SWI-Prolog branch (stable or devel)
    required: false
    default: devel
  swi-prolog-version:
    description: SWI-Prolog version to install
    required: true
    default: latest

runs:
  using: 'composite'
  steps:
    - name: Setup proto and bun 
      uses: moonrepo/setup-toolchain@v0
      with:
        auto-install: true

    - name: Install npm dependencies
      shell: bash
      run: bun install

    - name: Setup SWI-Prolog
      shell: bash
      run: bun run src/setup-swi-prolog.js

branding:
  icon: 'box'
  color: 'blue'
